#NDFilter_LightSource_Pattern_EyeboxID_ColorFilter_Custom (folder Structure Type2)
#Base_ImageName_Rule can include:
#1.NDFilter
#2.LightSource
#3.Pattern
#4.EyeboxID
#5.ColorFilterasync
#6.Custom

[ImageName]
Base_ImageName_Rule=NDFilter_LightSource_Pattern_EyeboxID_ColorFilter
Custom=
